### ISSUE TITLE
ERROR:  function cstore_clean_table_resources(oid) does not exist

### ISSUE THREAD

**Issue by seanpringle** [citusdata/cstore_fdw#125] opened 2016-10-21 05:28 UTC
Running:

```
PostgreSQL 9.6.0
cstore_fdw v1.5
Centos 6
```

It is possible to break DROP TABLE in schemas other than the one in which cstore_fdw was loaded:

```
psql (9.6.0)
Type "help" for help.

nci=# show role;
   role   
----------
 postgres
(1 row)

nci=# show search_path;
   search_path   
-----------------
 "$user", public
(1 row)

nci=# create extension cstore_fdw;
CREATE EXTENSION
nci=# create schema abc;
CREATE SCHEMA
nci=# set search_path to abc;
SET
nci=# create table t1 (c1 int);
CREATE TABLE
nci=# drop table t1;
ERROR:  function cstore_clean_table_resources(oid) does not exist
LINE 1: SELECT cstore_clean_table_resources(v_obj.objid)
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
QUERY:  SELECT cstore_clean_table_resources(v_obj.objid)
CONTEXT:  PL/pgSQL function cstore_drop_trigger() line 10 at PERFORM
```

The work around is to set search_path:

```
nci=# set search_path to abc, public;
SET
nci=# drop table t1;
DROP TABLE
nci=#
```

Is this the intended behavior?

**Comment by mtuncer** [comment] 2016-10-21 06:11
No it's not an intended behavior. Needs to be fixed.

Thanks for reporting.

**Comment by komamitsu** [comment] 2017-02-22 04:15
We experienced the same error. Could you give me some more information about this error? Thanks
- How often does the error occur?
- Is there any workaround of the error?
- When will the error be fixed?

**Comment by mtuncer** [comment] 2017-02-22 11:18
Looks like changing trigger function  ```cstore_drop_trigger``` to add ```public``` to function call to ```cstore_clean_table_resources```  like ```public.cstore_clean_table_resources(v_obj.objid);``` fixes the issue. 

This is going to be addressed in next cstore release.  Unfortunately I can't provide an accurate timing at this time.

Meanwhile as a workaround please run following to fix the function.

```sql
CREATE OR REPLACE FUNCTION cstore_drop_trigger()
	RETURNS event_trigger
	LANGUAGE plpgsql
	AS $csdt$
DECLARE v_obj record;
BEGIN
	FOR v_obj IN SELECT * FROM pg_event_trigger_dropped_objects() LOOP

		IF v_obj.object_type NOT IN ('table', 'foreign table') THEN
			CONTINUE;
		END IF;

		PERFORM public.cstore_clean_table_resources(v_obj.objid);

	END LOOP;
END;
$csdt$;
```

**Comment by komamitsu** [comment] 2017-02-22 11:39
@mtuncer Thanks! I'll try the workaround.

**Comment by WrathOfChris** [comment] 2017-02-23 07:32
Thanks @mtuncer the workaround works for us.

**Comment by nurse** [comment] 2017-06-12 11:28
When this is merged? I hit the issue again ;-(

**Comment by mtuncer** [comment] 2017-06-12 12:01
Hi @nurse 
I just merged it to develop branch. Main branch will be updated with the next cstore_fdw release.

**Comment by nurse** [comment] 2017-06-13 05:51
@mtuncer sure, thanks!

**Closed** 2017-07-22 01:36 UTC
Labels: bug, fixed-in-development-version, v1.6
