### ISSUE TITLE
cstore incompatible to 9.5 RC1

### ISSUE THREAD

**Issue by MahatmaFatalError** [citusdata/cstore_fdw#76] opened 2015-12-31 14:02 UTC
in the current feature_9.5_compatibility branch the following error appears:

make install
clang -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument -O2  --std=c99 -I. -I./ -I/usr/local/Cellar/postgresql/9.5rc1_2/include/server -I/usr/local/Cellar/postgresql/9.5rc1_2/include/internal -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/libxml2   -c -o cstore.pb-c.o cstore.pb-c.c
clang -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument -O2  --std=c99 -I. -I./ -I/usr/local/Cellar/postgresql/9.5rc1_2/include/server -I/usr/local/Cellar/postgresql/9.5rc1_2/include/internal -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/libxml2   -c -o cstore_fdw.o cstore_fdw.c

**cstore_fdw.c:748:29: warning**: incompatible pointer types assigning to 'GetForeignPlan_function' (aka 'ForeignScan *(*)(PlannerInfo
      *, RelOptInfo *, Oid, ForeignPath *, List *, List *, Plan *)') from 'ForeignScan *(PlannerInfo *, RelOptInfo *, Oid,
      ForeignPath *, List *, List *)' [-Wincompatible-pointer-types]
        fdwRoutine->GetForeignPlan = CStoreGetForeignPlan;
                                   ^ ~~~~~~~~~~~~~~~~~~~~
__cstore_fdw.c:1139:20: error__: too few arguments to function call, expected 9, have 8
                                                                                                           NIL); /* no fdw...
                                                                                                              ^
/usr/local/Cellar/postgresql/9.5rc1_2/include/server/optimizer/pathnode.h:82:1: note: 'create_foreignscan_path' declared here
extern ForeignPath *create_foreignscan_path(PlannerInfo *root, RelOptInfo *rel,
^
__cstore_fdw.c:1180:40: error__: too few arguments to function call, expected 8, have 7
                                                                   foreignPrivateList, NIL, NIL);
                                                                                               ^
/usr/local/Cellar/postgresql/9.5rc1_2/include/server/optimizer/planmain.h:46:1: note: 'make_foreignscan' declared here
extern ForeignScan *make_foreignscan(List *qptlist, List *qpqual,
^
1 warning and 2 errors generated.
make: *** [cstore_fdw.o] Error 1

**Comment by mtuncer** [comment] 2016-01-05 17:27
Hi @MahatmaFatalError 

This was caused by api re-change on postgresql side. I will look into it soon.

**Comment by devrimgunduz** [comment] 2016-01-06 08:03
PostgreSQL 9.5.0 will be out tomorrow. Any chance to fix this today, along with a new release, so that we can push the packages? Thanks!

**Comment by mtuncer** [comment] 2016-01-06 08:38
@devrimgunduz change in RC1 is little bit more than just enabling the build with NULL values.  I don't think I can squeeze them in today.  Tomorrow perhaps.

**Comment by mtuncer** [comment] 2016-01-07 09:30
@MahatmaFatalError  @devrimgunduz build failures are fixed in feature_9.5_compatibility branch. Verified regression tests pass.

**Comment by mtuncer** [comment] 2016-01-07 13:29
Please note that this branch is 9.5 specific. It will not build against earlier version at this time. Release 1.4 of cstore_fdw will be compatible with both 9.5 and pre-9.5 version. It will also have truncate table support.

**Comment by bobelev** [comment] 2016-01-08 14:03
@mtuncer any information on release date of 1.4?

**Comment by tylerFowler** [comment] 2016-01-10 00:54
+1 this is the only thing stopping me from upgrading to PG 9.5

**Closed** 2016-01-10 18:10 UTC
